// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDriver = `-- name: CreateDriver :one
insert into drivers(id, user_id,cnh_number, vehicle_id)
VALUES($1, $2, $3, $4)
RETURNING id, user_id,cnh_number, vehicle_id
`

type CreateDriverParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CnhNumber string    `json:"cnh_number"`
	VehicleID uuid.UUID `json:"vehicle_id"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (*Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.ID,
		arg.UserID,
		arg.CnhNumber,
		arg.VehicleID,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CnhNumber,
		&i.VehicleID,
	)
	return &i, err
}

const existsDriver = `-- name: ExistsDriver :one
select EXISTS(
    SELECT 1 from drivers
    where user_id = $1 or cnh_number = $2
)
`

type ExistsDriverParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CnhNumber string    `json:"cnh_number"`
}

func (q *Queries) ExistsDriver(ctx context.Context, arg ExistsDriverParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsDriver, arg.UserID, arg.CnhNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
