// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CnhNumber string    `json:"cnh_number"`
	VehicleID uuid.UUID `json:"vehicle_id"`
}

type Ride struct {
	ID                 uuid.UUID          `json:"id"`
	PassengerID        uuid.UUID          `json:"passenger_id"`
	DriverID           pgtype.UUID        `json:"driver_id"`
	OriginAddress      string             `json:"origin_address"`
	OriginLat          float64            `json:"origin_lat"`
	OriginLng          float64            `json:"origin_lng"`
	DestinationAddress string             `json:"destination_address"`
	DestinationLat     float64            `json:"destination_lat"`
	DestinationLng     float64            `json:"destination_lng"`
	StatusID           uuid.UUID          `json:"status_id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	MonetaryValue      pgtype.Numeric     `json:"monetary_value"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type RideStatus struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	PhotoUrl  string             `json:"photo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Vehicle struct {
	ID           uuid.UUID `json:"id"`
	LicensePlate string    `json:"license_plate"`
	Model        string    `json:"model"`
	Brand        string    `json:"brand"`
	Color        string    `json:"color"`
}
