// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDriver(ctx context.Context, arg CreateDriverParams) (*Driver, error)
	CreateRide(ctx context.Context, arg CreateRideParams) (*CreateRideRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (*Vehicle, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ExistsDriver(ctx context.Context, arg ExistsDriverParams) (bool, error)
	ExistsUserByEmail(ctx context.Context, email string) (bool, error)
	ExistsVehicle(ctx context.Context, licensePlate string) (bool, error)
	FindSafeUserByEmail(ctx context.Context, email string) (*FindSafeUserByEmailRow, error)
	FindUserByEmail(ctx context.Context, email string) (*FindUserByEmailRow, error)
	GetRideFromDriver(ctx context.Context, arg GetRideFromDriverParams) (uuid.UUID, error)
	UpdateRide(ctx context.Context, arg UpdateRideParams) (*UpdateRideRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
