// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rides.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRide = `-- name: CreateRide :one
insert into rides(
    id,
    destination_address, 
    destination_lat, 
    destination_lng,
 
    origin_address, 
    origin_lat, 
    origin_lng, 

    passenger_id
    )
values ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id,destination_address,destination_lat,destination_lng,origin_address,origin_lat,origin_lng,passenger_id,status_id
`

type CreateRideParams struct {
	ID                 uuid.UUID `json:"id"`
	DestinationAddress string    `json:"destination_address"`
	DestinationLat     float64   `json:"destination_lat"`
	DestinationLng     float64   `json:"destination_lng"`
	OriginAddress      string    `json:"origin_address"`
	OriginLat          float64   `json:"origin_lat"`
	OriginLng          float64   `json:"origin_lng"`
	PassengerID        uuid.UUID `json:"passenger_id"`
}

type CreateRideRow struct {
	ID                 uuid.UUID `json:"id"`
	DestinationAddress string    `json:"destination_address"`
	DestinationLat     float64   `json:"destination_lat"`
	DestinationLng     float64   `json:"destination_lng"`
	OriginAddress      string    `json:"origin_address"`
	OriginLat          float64   `json:"origin_lat"`
	OriginLng          float64   `json:"origin_lng"`
	PassengerID        uuid.UUID `json:"passenger_id"`
	StatusID           string    `json:"status_id"`
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (*CreateRideRow, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.ID,
		arg.DestinationAddress,
		arg.DestinationLat,
		arg.DestinationLng,
		arg.OriginAddress,
		arg.OriginLat,
		arg.OriginLng,
		arg.PassengerID,
	)
	var i CreateRideRow
	err := row.Scan(
		&i.ID,
		&i.DestinationAddress,
		&i.DestinationLat,
		&i.DestinationLng,
		&i.OriginAddress,
		&i.OriginLat,
		&i.OriginLng,
		&i.PassengerID,
		&i.StatusID,
	)
	return &i, err
}

const getActiveRideFromPassenger = `-- name: GetActiveRideFromPassenger :one
SELECT id, passenger_id, driver_id, origin_address, origin_lat, origin_lng, destination_address, destination_lat, destination_lng, status_id, started_at, ended_at, monetary_value, created_at, updated_at
FROM rides
WHERE passenger_id = $1
AND status_id IN (
    'WAITING_DRIVER',
    'STARTED_RIDE'
)
LIMIT 1
`

func (q *Queries) GetActiveRideFromPassenger(ctx context.Context, passengerID uuid.UUID) (*Ride, error) {
	row := q.db.QueryRow(ctx, getActiveRideFromPassenger, passengerID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.OriginAddress,
		&i.OriginLat,
		&i.OriginLng,
		&i.DestinationAddress,
		&i.DestinationLat,
		&i.DestinationLng,
		&i.StatusID,
		&i.StartedAt,
		&i.EndedAt,
		&i.MonetaryValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRideFromDriver = `-- name: GetRideFromDriver :one
select
    id
from 
    rides
where 
    driver_id = $1 and
    status_id = $2
`

type GetRideFromDriverParams struct {
	DriverID pgtype.UUID `json:"driver_id"`
	StatusID string      `json:"status_id"`
}

func (q *Queries) GetRideFromDriver(ctx context.Context, arg GetRideFromDriverParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRideFromDriver, arg.DriverID, arg.StatusID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRideFromPassenger = `-- name: GetRideFromPassenger :one
select
    id
from 
    rides
where 
    passenger_id = $1 and
    status_id = $2
`

type GetRideFromPassengerParams struct {
	PassengerID uuid.UUID `json:"passenger_id"`
	StatusID    string    `json:"status_id"`
}

func (q *Queries) GetRideFromPassenger(ctx context.Context, arg GetRideFromPassengerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRideFromPassenger, arg.PassengerID, arg.StatusID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRide = `-- name: UpdateRide :one
UPDATE rides
SET 
    status_id = COALESCE($1, status_id),
    driver_id = COALESCE($2, driver_id)
WHERE 
    id = $3
RETURNING id, passenger_id, driver_id, status_id
`

type UpdateRideParams struct {
	StatusID string      `json:"status_id"`
	DriverID pgtype.UUID `json:"driver_id"`
	ID       uuid.UUID   `json:"id"`
}

type UpdateRideRow struct {
	ID          uuid.UUID   `json:"id"`
	PassengerID uuid.UUID   `json:"passenger_id"`
	DriverID    pgtype.UUID `json:"driver_id"`
	StatusID    string      `json:"status_id"`
}

func (q *Queries) UpdateRide(ctx context.Context, arg UpdateRideParams) (*UpdateRideRow, error) {
	row := q.db.QueryRow(ctx, updateRide, arg.StatusID, arg.DriverID, arg.ID)
	var i UpdateRideRow
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.StatusID,
	)
	return &i, err
}
