// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rides.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRide = `-- name: CreateRide :one
insert into rides(
    destination_address, 
    destination_lat, 
    destination_lng,
 
    origin_address, 
    origin_lat, 
    origin_lng, 

    passenger_id
    )
values ($1, $2, $3, $4, $5, $6, $7)
RETURNING id,destination_address,destination_lat,destination_lng,origin_address,origin_lat,origin_lng,passenger_id,status_id
`

type CreateRideParams struct {
	DestinationAddress string    `json:"destination_address"`
	DestinationLat     float64   `json:"destination_lat"`
	DestinationLng     float64   `json:"destination_lng"`
	OriginAddress      string    `json:"origin_address"`
	OriginLat          float64   `json:"origin_lat"`
	OriginLng          float64   `json:"origin_lng"`
	PassengerID        uuid.UUID `json:"passenger_id"`
}

type CreateRideRow struct {
	ID                 uuid.UUID `json:"id"`
	DestinationAddress string    `json:"destination_address"`
	DestinationLat     float64   `json:"destination_lat"`
	DestinationLng     float64   `json:"destination_lng"`
	OriginAddress      string    `json:"origin_address"`
	OriginLat          float64   `json:"origin_lat"`
	OriginLng          float64   `json:"origin_lng"`
	PassengerID        uuid.UUID `json:"passenger_id"`
	StatusID           uuid.UUID `json:"status_id"`
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (*CreateRideRow, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.DestinationAddress,
		arg.DestinationLat,
		arg.DestinationLng,
		arg.OriginAddress,
		arg.OriginLat,
		arg.OriginLng,
		arg.PassengerID,
	)
	var i CreateRideRow
	err := row.Scan(
		&i.ID,
		&i.DestinationAddress,
		&i.DestinationLat,
		&i.DestinationLng,
		&i.OriginAddress,
		&i.OriginLat,
		&i.OriginLng,
		&i.PassengerID,
		&i.StatusID,
	)
	return &i, err
}

const isRideFromUser = `-- name: IsRideFromUser :one
select EXISTS(
    select 1 from rides
    where id = $1 and passenger_id = $2 and driver_id = $3
)
`

type IsRideFromUserParams struct {
	ID          uuid.UUID   `json:"id"`
	PassengerID uuid.UUID   `json:"passenger_id"`
	DriverID    pgtype.UUID `json:"driver_id"`
}

func (q *Queries) IsRideFromUser(ctx context.Context, arg IsRideFromUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRideFromUser, arg.ID, arg.PassengerID, arg.DriverID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRide = `-- name: UpdateRide :one
UPDATE rides
SET status_id = '730e3d5c-5abf-44e1-86d9-697014eee856', driver_id = $2
WHERE id = $1
RETURNING id, passenger_id, driver_id
`

type UpdateRideParams struct {
	ID       uuid.UUID   `json:"id"`
	DriverID pgtype.UUID `json:"driver_id"`
}

type UpdateRideRow struct {
	ID          uuid.UUID   `json:"id"`
	PassengerID uuid.UUID   `json:"passenger_id"`
	DriverID    pgtype.UUID `json:"driver_id"`
}

func (q *Queries) UpdateRide(ctx context.Context, arg UpdateRideParams) (*UpdateRideRow, error) {
	row := q.db.QueryRow(ctx, updateRide, arg.ID, arg.DriverID)
	var i UpdateRideRow
	err := row.Scan(&i.ID, &i.PassengerID, &i.DriverID)
	return &i, err
}
