// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password,photo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email,photo_url
`

type CreateUserParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	PhotoUrl string    `json:"photo_url"`
}

type CreateUserRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	PhotoUrl string    `json:"photo_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhotoUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhotoUrl,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) ExistsUserByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findSafeUserByEmail = `-- name: FindSafeUserByEmail :one
SELECT id,name,email,created_at,deleted_at, photo_url FROM users WHERE email = $1
`

type FindSafeUserByEmailRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	PhotoUrl  string             `json:"photo_url"`
}

func (q *Queries) FindSafeUserByEmail(ctx context.Context, email string) (*FindSafeUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findSafeUserByEmail, email)
	var i FindSafeUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.PhotoUrl,
	)
	return &i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT 
    users.id, 
    name, 
    email, 
    password,
    photo_url,
    drivers.id as "driver_id"
FROM 
    users
left join drivers on drivers.user_id = users.id
WHERE email ilike $1
`

type FindUserByEmailRow struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	PhotoUrl string      `json:"photo_url"`
	DriverID pgtype.UUID `json:"driver_id"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (*FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.PhotoUrl,
		&i.DriverID,
	)
	return &i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, email = $3, password = $4, deleted_at = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.DeletedAt,
	)
	return err
}
