// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createVehicle = `-- name: CreateVehicle :one
insert into vehicles(id, license_plate, model, brand, color)
VALUES($1, $2, $3, $4, $5)
RETURNING id, license_plate, model, brand, color
`

type CreateVehicleParams struct {
	ID           uuid.UUID `json:"id"`
	LicensePlate string    `json:"license_plate"`
	Model        string    `json:"model"`
	Brand        string    `json:"brand"`
	Color        string    `json:"color"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (*Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.ID,
		arg.LicensePlate,
		arg.Model,
		arg.Brand,
		arg.Color,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.Model,
		&i.Brand,
		&i.Color,
	)
	return &i, err
}

const existsVehicle = `-- name: ExistsVehicle :one
select EXISTS(
    select 1 from vehicles
    where license_plate ilike $1
)
`

func (q *Queries) ExistsVehicle(ctx context.Context, licensePlate string) (bool, error) {
	row := q.db.QueryRow(ctx, existsVehicle, licensePlate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
